# Generated by Django 5.1.7 on 2025-05-15 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_hostel_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel_owner',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
