# Generated by Django 5.1.7 on 2025-05-16 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_hostelowner_options_alter_hostelowner_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='price_per_month',
        ),
        migrations.AddField(
            model_name='room',
            name='monthly_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.IntegerField(),
        ),
    ]
