# Generated by Django 5.1.7 on 2025-05-16 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_remove_room_price_per_month_room_monthly_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.IntegerField(default=2),
        ),
    ]
