# Generated by Django 5.1.7 on 2025-05-19 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_alter_room_capacity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostelrentpayment',
            name='address',
        ),
        migrations.RemoveField(
            model_name='hostelrentpayment',
            name='phone_number',
        ),
        migrations.DeleteModel(
            name='Hostel_Owner',
        ),
    ]
