# Generated by Django 5.2.3 on 2025-06-12 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('members', '0009_alter_hostelowner_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostelowner',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='hostelowner_set', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='hostelowner',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='hostelowner_set', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
