# Generated by Django 5.2.3 on 2025-06-12 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_alter_hostelowner_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostelowner',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hostelowner',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hostelowner',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
