# Generated by Django 5.2.3 on 2025-08-02 19:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_alter_hostelowner_address_alter_hostelowner_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentpayment',
            name='due_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='rentpayment',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
